### ISSUE TITLE
Quantum espresso and lammps do not compile when you try to statistically link PLUMED

### ISSUE THREAD

**Issue by gtribello** [plumed-testcenter/plumed-testcenter#2]
You can see this problem for lammps on the dashboard page here:

https://plumed-testcenter.github.io/browse.html

In the standard error for the build with v2.9 which you can get from https://plumed-testcenter.github.io/tests/lammps/install.html you find the error message is:

````
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o): in function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x1d): undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o): in function `MPI::Intracomm::Clone() const':
(.text._ZNK3MPI9Intracomm5CloneEv[_ZNK3MPI9Intracomm5CloneEv]+0x40): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o): in function `MPI::Graphcomm::Clone() const':
(.text._ZNK3MPI9Graphcomm5CloneEv[_ZNK3MPI9Graphcomm5CloneEv]+0x3b): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o): in function `MPI::Cartcomm::Sub(bool const*) const':
(.text._ZNK3MPI8Cartcomm3SubEPKb[_ZNK3MPI8Cartcomm3SubEPKb]+0x96): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o): in function `MPI::Intracomm::Create_graph(int, int const*, int const*, bool) const':
(.text._ZNK3MPI9Intracomm12Create_graphEiPKiS2_b[_ZNK3MPI9Intracomm12Create_graphEiPKiS2_b]+0x42): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o): in function `MPI::Cartcomm::Clone() const':
(.text._ZNK3MPI8Cartcomm5CloneEv[_ZNK3MPI8Cartcomm5CloneEv]+0x3b): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o):(.text._ZNK3MPI9Intracomm11Create_cartEiPKiPKbb[_ZNK3MPI9Intracomm11Create_cartEiPKiPKbb]+0xab): more undefined references to `MPI::Comm::Comm()' follow
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o):(.data.rel.ro._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: /home/runner/opt/lib/libplumed.a(kernel.o):(.data.rel.ro._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `MPI::Win::Free()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lmp.dir/build.make:109: lmp] Error 1
make[1]: *** [CMakeFiles/Makefile2:198: CMakeFiles/lmp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
+ '[' -f ./lmp ']'
````

A similar problem occurs when you try to link quantum espresso using the static plumed library.

**Comment by gtribello** [comment]
Well the static linking of espresso is at least working now.
